name: '🚀 Feature request'
description: Suggest an idea or enhancement.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea or improvement for this project.
        Please complete the below form to ensure we have all the details to investigate further.
  - type: textarea
    id: solution
    attributes:
      label: 💡 Idea
      description: |
        Please describe the desired behavior, pitch your idea, or suggest improvements
    validations:
      required: true
  - type: input
    id: bugrelation
    attributes:
      label: Is your feature related to an existing issue?
      description: |
        Refer to a an existing issue by number (for example, #100).
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Design Notes
      description: |
        Have you considered alternative solutions or implementations? Do you have an idea on how this should be implemented? Let us know!
