name: 'RESTler Full Build'
description: 'Build and publish RESTler projects'
inputs:
  build_configuration:
    description: 'Build configuration'
    required: true
  version_number:
    description: 'Version number'
    required: true
  build_platform:
    description: 'Build platform'
    required: true
  shell:
    description: 'Shell to use for run steps'
    required: true
    default: 'pwsh'

runs:
  using: 'composite'
  steps:
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.x'

    - name: Use NuGet 5.8
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: '5.8.0'

    - name: Restore NuGet packages
      run: nuget restore **/Restler.sln
      shell: ${{ inputs.shell }}

    - name: Clean solution
      run: dotnet clean src/compiler/Restler.CompilerExe/Restler.CompilerExe.fsproj src/driver/Restler.Driver.fsproj src/ResultsAnalyzer/ResultsAnalyzer.fsproj -c ${{ inputs.build_configuration }}
      shell: ${{ inputs.shell }}

    - name: Publish RESTler dotnet core projects
      run: dotnet publish src/compiler/Restler.CompilerExe/Restler.CompilerExe.fsproj src/driver/Restler.Driver.fsproj src/ResultsAnalyzer/ResultsAnalyzer.fsproj --no-restore -c ${{ inputs.build_configuration }} /p:version=${{ inputs.version_number }} /p:Platform=${{ inputs.build_platform }}
      shell: ${{ inputs.shell }}

    - name: Build unit tests
      run: dotnet build src/compiler/Restler.Compiler.Test/Restler.Compiler.Test.fsproj --no-restore -c ${{ inputs.build_configuration }}
      shell: ${{ inputs.shell }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'