name: 'Compiler Functional Tests'
description: 'Run compiler functional tests'
inputs:
  build_configuration:
    description: 'Build configuration'
    required: true
  build_platform:
    description: 'Build platform'
    required: true
  shell:
    description: 'Shell to use for run steps'
    required: true
    default: 'pwsh'

runs:
  using: 'composite'
  steps:
    - name: Clean solution for functional tests
      run: dotnet clean src/compiler/Restler.Compiler.Test/Restler.Compiler.Test.fsproj -c ${{ inputs.build_configuration }}
      shell: ${{ inputs.shell }}

    - name: Build functional tests
      run: dotnet build src/compiler/Restler.Compiler.Test/Restler.Compiler.Test.fsproj --no-restore -c ${{ inputs.build_configuration }}
      shell: ${{ inputs.shell }}

    - name: Create TestResults directory
      run: |
        mkdir -p ${{ github.workspace }}/src/TestResults
        echo "TEST_RESULTS_DIR=${{ github.workspace }}/src/TestResults" >> $GITHUB_ENV
      shell: ${{ inputs.shell }}

    - name: Run functional tests
      run: dotnet test src/compiler/Restler.Compiler.Test/Restler.Compiler.Test.fsproj -c ${{ inputs.build_configuration }} --no-build --logger "trx;LogFileName=${{ env.TEST_RESULTS_DIR }}/test_results.trx"
      shell: ${{ inputs.shell }}

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{ env.TEST_RESULTS_DIR }}/test_results.trx

    - name: Display test summary
      if: always()
      uses: test-summary/action@v2
      with:
        paths: ${{ env.TEST_RESULTS_DIR }}/test_results.trx